refactor check to exclude the date

diff --git a/.github/workflows/check_man_pages.yml b/.github/workflows/check_man_pages.yml
--- a/.github/workflows/check_man_pages.yml
+++ b/.github/workflows/check_man_pages.yml
@@ -22,4 +22,20 @@ jobs:
         run: ${{github.workspace}}/docs/generate_man_pages.sh
 
       - name: Check result
-        run: git diff --exit-code
+        run: |
+          set -xe
+          EXIT_CODE=0
+          # Match any line that begins with '+' and does not contain a month name. grep will return
+          # a nonzero exit code if there's no matches, but that's what we want. In that case, the
+          # bit after '||' will execute and prevent the job from failing.
+          git diff | grep -Po '(?!.*(January|February|March|April|May|June|July|August|September|October|November|December))^\+[^\+].*' || EXIT_CODE=$?
+          # If there was a match, then grep returns a zero exit code and we want to return a nonzero exit code.
+          if [ "$EXIT_CODE" == 0 ]; then
+              echo "Manual pages are out of sync. Please regenerate with 'docs/generate_man_pages.sh' or apply the following diff:"
+              git diff | cat
+              exit 1
+          else
+              exit 0
+          fi
+        shell: bash
+
